### ISSUE TITLE
mistype in section #3?

### ISSUE THREAD

**Issue by rafaellaurenti** [brightway-lca/brightway-book#50]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[53], line 2
      1 #One way of manually creating a database:
----> 2 db1 = bw.Database('3D') 
      3 db1.register()
      4 db1.write({('3D', 'Printer'):{
      5     'name': 'Printer',
      6     'exchanges': [],
   (...)
      9     'categories': ('in the', 'universe')
     10 }})

NameError: name 'bw' is not defined

Souldn't ot be db1 = bd.Database('3D') ?

**Comment by ChristinaKockel** [comment]
This continues throughout the script. Everywhere methods and databases is used, I think it should be bd. instead of bw.
