### ISSUE TITLE
Importing in BW processes written in SP

### ISSUE THREAD

**Issue by GiuliaCavenago93** [brightway-lca/brightway-book#52]
Dear Brightway community,
I am currently investigating the feasibility of importing processes created in SimaPro directly into Brightway. While I have successfully managed to achieve this by manually creating Excel files containing the necessary information required by Brightway (e.g., name, reference product, location), I am curious to explore if there exists an automated method for this task. 

Specifically, I am wondering if there is a function or tool within Brightway that facilitates the direct import of processes written in SP and exported in Ecospold v1 format. Despite attempting to follow the same procedure employed for importing the ecoinvent database, I have encountered difficulties in replicating the process.

I would appreciate any guidance or assistance someone could provide in this, I guess you might have encounter the same problems.

Thank you very much!

@cmutel

**Comment by michaelweinold** [comment]
Off topic here - please use [the mailing](https://docs.brightway.dev/en/latest/content/contact/contact.html) list, or another more appropriate repository.
