### ISSUE TITLE
Illustrate importing EI with ecoinvent_interface

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway-book#54]
## Current

There is a section of the book for bw25 where we show [how to import EI db](https://learn.brightway.dev/en/latest/content/notebooks/BW25_for_beginners.html#a-importing-ecoinvent) using the ecospold single output importer, directly from ecoinvent downloaded files.

## Expected

Illustrate _also_ how to import ecoinvent using the [ecoinvent_interface](https://github.com/brightway-lca/ecoinvent_interface) package.

**Comment by tngTUDOR** [comment]
🤭 I have gist that gives already some working code:

[import ecoinvent in 2 lines](https://gist.github.com/tngTUDOR/947f60a5ed965d8d1135b5e4eb5455a3)

**Comment by michaelweinold** [comment]
Adding @alyabolowich and @KarinTreyer to this conversation 😇
