### ISSUE TITLE
 PackagesNotFoundError: 

### ISSUE THREAD

**Issue by juliana-steinbach** [brightway-lca/brightway-book#65]
(base) C:\Users\jsteinbach>conda create -n bw brightway2=2.4.7 jupyterlab
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - brightway2=2.4.7

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by michaelweinold** [comment]
Fixed by adding `-c conda-forge` to conda install command. Will be updated in a few minutes.
