### ISSUE TITLE
Unable to Access env_bw25.yml File for Conda Environment Setup in Brightway

### ISSUE THREAD

**Issue by diptavasius** [brightway-lca/brightway-book#67]
I’m new to Python and recently completed a basic Python course. I’m now exploring Python-based Life Cycle Assessment (LCA) tools, so I apologize in advance if my question seems too basic.

I’m trying to set up my first project, but I’m having trouble downloading the necessary packages for Conda. Specifically, I’m trying to use
`env_bw25.yml` , but the link provided on [this GitHub page](https://github.com/brightway-lca/brightway-book/raw/refs/heads/main/content/chapters/BW2/_environment/env_bw25.yml) seems to be unavailable. This prevents me from executing the command:
`conda env create -f env_bw25.yml --solver libmamba`

Could someone please help or guide me on how to proceed?

**Comment by michaelweinold** [comment]
Hello, hello! The link has been fixed - unfortunately, the file download is currently not possible due to a readthedocs.org limitation. However, if you click it - it will show you the recipe
