### ISSUE TITLE
Deprecated  bi.bw2setup() recommended as installation option

### ISSUE THREAD

**Issue by CristinaMadrid** [brightway-lca/brightway-book#68]
I am not sure how to change it myself. I think it is important to review:
https://learn.brightway.dev/en/latest/content/chapters/BW25/BW25_introduction.html#option-b

That recommends 

```
 bi.bw2setup() 
```
for Biosphere3 installation instead of  
```
bi.remote.install_project('<project_tag>', '<my_desired_project_name>')
```

Thanks!

**Comment by michaelweinold** [comment]
Hello, hello! The command `bi.bw2setup()` is listed only as "Option B". Is there something you would like to change? If so, what exactly?

**Comment by CristinaMadrid** [comment]
Hi Michael,
Well is not truly option B as it is deprecated. It does not work , the proper option now , if I got it right is: 
```
bi.remote.install_project('Tagname', 'Projectname')
```

Would be happy to rewrite the section myself but I am a dummy with forking etc.

**Comment by michaelweinold** [comment]
Ah, now I see what you mean. I have updated the section. Thank you for raising this issue!
